FROM golang:latest AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o /lana-sre-challenge

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /lana-sre-challenge /lana-sre-.challenge

EXPOSE 3000

USER nonroot:nonroot

ENTRYPOINT ["/lana-sre-challenge"]

