version: "3.7"

services:
  docker-golang-api-test:
    depends_on:
      - roach-database
    build:
      context: .
    container_name: golang-api-test
    hostname: golang-api-test
    networks:
      - mynet
    ports:
      - 3000:3000
    environment:
      - PGUSER=${PGUSER:-root}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE-postgres}
    deploy:
      restart_policy:
        condition: on-failure
  roach-database:
    image: cockroachdb/cockroach:latest
    container_name: roach-database
    hostname: db
    networks:
      - mynet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-database
    command: start-single-node --insecure

volumes:
  roach:

networks:
  mynet:
    driver: bridge
